# Generated by Django 4.2.2 on 2023-06-22 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
        ('users', '0002_rename_full_name_customuser_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='institute.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='designation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='institute.designation'),
            preserve_default=False,
        ),
    ]
