# Generated by Django 4.2.2 on 2023-06-22 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_course_couse_code_course_name'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.designation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.question')),
            ],
        ),
    ]
