# Generated by Django 4.2.2 on 2023-06-22 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_course_couse_code_course_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
